### ISSUE TITLE
Account Add not working

### ISSUE THREAD

**Issue by Tetee11** [Solybum/Tethealla#1]
Al utilizar el accountadd.exe y llenar los datos estos se agregan a la base de datos, pero al intentar ingresar en el cliente siempre te dice que el account o el password es incorrecto. Esto no sucede con el Account add del viejo codigo.

**Comment by Solybum** [comment]
Creo que el problema ha sido resuelto en ed222d99096ac6ffc4dda7c17478017104e3124e.
El hash es el mismo que el account_add original, aunque tome la oportunidad para remover la division por 3600 que hacia el regtime tviera una diferencia minima de 1 hora, ahora el regtime se diferencia por segundo.
